##### hydra
hydra:
    run:
      dir: ./outputs/${exp_name}/${status}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    sweep:
      dir: ./outputs/${exp_name}/${status}/${now:%Y-%m-%d}_${now:%H-%M-%S}
      subdir: ${hydra.job.override_dirname}

##### dir
exp_name: poisson_deblurring  # experiment name: poisson_deblurring | ifdwdnet
tester_name: poisson_deblurring_tester # tester name: poisson_deblurring_tester | ifdwdnet_tester
status: exp        # run status: train|test|debug
checkpoint: ${hydra:runtime.cwd}/model_zoo/ckp.pth    # loading checkpoint
outputs_dir: outputs/

##### run
gpus: [0]           # GPU used, Warning: Only one GPU is supported for 'test' now
num_workers: 16      # number of cpu worker

# network architecture
arch:
  _target_: srcs.model.poisson_deblurring_model.P4IP_Net

# noise level
kc: 8

##### metrics
metrics:
  - _target_: srcs.metric.metric.calc_psnr
  - _target_: srcs.metric.metric.calc_ssim

##### data&nets
defaults:
  - data: poisson_deblurring_exp_data #  benchmark
  - override hydra/job_logging : custom # custom || colorlog
  - override hydra/hydra_logging: colorlog
  - _self_